SET SERVEROUTPUT ON;
DECLARE
  CURSOR config_table_cur
  IS
    SELECT 
        *
    FROM 
        config_table;
        
    tab_name varchar2(50);
    drop_sql varchar2(100);
    row_count number(10):= 0;
BEGIN
  FOR i IN config_table_cur
  LOOP
      tab_name:= i.table_name;  
      DBMS_OUTPUT.PUT_LINE('--------------------------');

      SELECT count(*) into row_count FROM user_tables where table_name = tab_name;
       IF(row_count > 0)
        THEN
            drop_sql:= 'DROP TABLE ' || tab_name || ' CASCADE CONSTRAINTS PURGE'; 
            EXECUTE IMMEDIATE drop_sql;
            DBMS_OUTPUT.PUT_LINE('TABLE '|| tab_name || ' DROPPED');
         END IF;
  END LOOP;
  EXECUTE IMMEDIATE 'DROP TABLE CONFIG_TABLE';
  dbms_output.put_line( 'ALL TABLES DROPPED ');
END;
/




DECLARE
ROW_COUNT NUMBER(10);
CHECK_CONSTRAINT_VIOLATED EXCEPTION;
PRAGMA EXCEPTION_INIT(CHECK_CONSTRAINT_VIOLATED, -2290);
BEGIN 
    SELECT count(*) into ROW_COUNT FROM user_tables where table_name = 'CONFIG_TABLE';
    IF(ROW_COUNT > 0)
    THEN
        DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE ALREADY EXISTS');
    ELSE
        EXECUTE IMMEDIATE 'CREATE TABLE CONFIG_TABLE
    (
       TABLE_NAME varchar2(50), 
       TABLE_DEF varchar2(3000) NOT NULL, 
       CONSTRAINT CONFIG_TABLE_PK PRIMARY KEY(TABLE_NAME)
    )
    ';    
     DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE CREATED SUCCESSFULLY');
     
    
    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('INSURANCE_COMPANY','CREATE TABLE INSURANCE_COMPANY
            (   
           COMPANY_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
           COMPANY_NAME VARCHAR2(100) NOT NULL,
           PHONE_NO NUMBER(10),
           STREET VARCHAR2(100),
           CITY VARCHAR2(50),
           STATE VARCHAR2(25),
           ZIPCODE VARCHAR2(6),
           CONSTRAINT INSURANCE_COMPANY_PK PRIMARY KEY(COMPANY_ID)
            )
    ')]';
    
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('AGENT','CREATE TABLE AGENT
            (   
           AGENT_ID NUMBER(6) GENERATED BY DEFAULT AS IDENTITY,
           COMPANY_ID NUMBER(10) NOT NULL,
         FIRST_NAME VARCHAR2(20) NOT NULL,
         LAST_NAME VARCHAR2(20)NOT NULL,
         PHONE NUMBER(10)  NOT NULL,
         EMAIL VARCHAR2(50) NOT NULL,
         CONSTRAINT AGENT_PK PRIMARY KEY(AGENT_ID),
         CONSTRAINT AGENT_FK_INSURANCE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES INSURANCE_COMPANY(COMPANY_ID)
            )
    ')]';
    
      EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('CORPORATE_CLIENTS','CREATE TABLE CORPORATE_CLIENTS
            (   
            CLIENT_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            COMPANY_ID NUMBER(10) NOT NULL,
            CLIENT_NAME VARCHAR2(30) NOT NULL,
            TOTAL_EMPLOYEES NUMBER(6) NOT NULL,
            CONSTRAINT CORPORATE_CLIENTS_PK PRIMARY KEY (CLIENT_ID),
            CONSTRAINT CORPORATE_CLIENTS_FK_INSURANCE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES INSURANCE_COMPANY(COMPANY_ID)
            )
    ')]';





    
    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('POLICY_CATALOGUE','CREATE TABLE POLICY_CATALOGUE
            (
              POLICY_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
              COMPANY_ID NUMBER(10) NOT NULL,
            PREMIUM VARCHAR2(10) NOT NULL,
            COPAY NUMBER(10) NOT NULL,
            TENURE NUMBER(10) NOT NULL,
            CONSTRAINT POLICY_CATALOGUE_PK PRIMARY KEY (POLICY_ID),
            CONSTRAINT POLICY_CATALOGUE_FK_INSURANCE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES INSURANCE_COMPANY(COMPANY_ID)
            )
       ')]';




        EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('CUSTOMER','CREATE TABLE CUSTOMER
            (
            CUSTOMER_ID NUMBER(10)GENERATED BY DEFAULT AS IDENTITY,
AGENT_ID NUMBER(6),
CLIENT_ID NUMBER(10),
FIRST_NAME VARCHAR2(30) NOT NULL,
LAST_NAME VARCHAR2(40) NOT NULL,
SSN NUMBER(9) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
STREET_NAME VARCHAR(100) NOT NULL,
CITY VARCHAR2(30) NOT NULL,
STATE VARCHAR2(30) NOT NULL,
ZIPCODE VARCHAR2(6),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT EMAIL_VALIDATION CHECK(REGEXP_LIKE(EMAIL,''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'')),
CONSTRAINT CUSTOMER_FK_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENT(AGENT_ID),
CONSTRAINT CUSTOMER_FK_CORPORATE_CLIENTS FOREIGN KEY (CLIENT_ID) REFERENCES CORPORATE_CLIENTS(CLIENT_ID)
              
                 )
       ')]';

     
    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('POLICY','CREATE TABLE POLICY
            (
            POLICY_NO NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            CUSTOMER_ID NUMBER(10) NOT NULL,
            POLICY_ID NUMBER(10) NOT NULL,
            POLICY_EXPIRY_DATE DATE NOT NULL,
            CONSTRAINT POLICY_PK PRIMARY KEY (POLICY_NO),
            CONSTRAINT POLICY_FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
            CONSTRAINT POLICY_FK_POLICY_CATALOGUE FOREIGN KEY (POLICY_ID) REFERENCES POLICY_CATALOGUE(POLICY_ID)
    )
    ')]';



        
       




    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('PATIENT','CREATE TABLE PATIENT
            (
             PATIENT_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            CUSTOMER_ID NUMBER(10) NOT NULL,
            FIRST_NAME VARCHAR2(20) NOT NULL,
            LAST_NAME VARCHAR2(20)NOT NULL,
            RELATIONSHIP VARCHAR2(20)NOT NULL,
            PATIENT_DOB VARCHAR2(20)NOT NULL,
            CONSTRAINT PATIENT_ID PRIMARY KEY (PATIENT_ID),
            CONSTRAINT PATIENT_FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
    )
    ')]';
    
       EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('HOSPITAL','CREATE TABLE HOSPITAL
            (
             HOSPITAL_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
HOSPITAL_NAME VARCHAR2(100) NOT NULL,
ADDRESS VARCHAR2(100) NOT NULL,
CITY VARCHAR2(30) NOT NULL,
STATE VARCHAR2(30) NOT NULL,
ZIPCODE VARCHAR2(6) NOT NULL,
CONSTRAINT HOSPITAL_ID PRIMARY KEY (HOSPITAL_ID)
    )
    ')]';
    
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('DOCTOR','CREATE TABLE DOCTOR
            (
            
            DOCTOR_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
HOSPITAL_ID NUMBER(10) NOT NULL,
FIRST_NAME VARCHAR2(20) NOT NULL,
LAST_NAME VARCHAR2(20)NOT NULL,
DEPARTMENT VARCHAR2(20)NOT NULL,    
CONSTRAINT DOCTOR_ID PRIMARY KEY (DOCTOR_ID),
CONSTRAINT DOCTOR_FK_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
             
    )
    ')]';
    
           
    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('TREATMENT','CREATE TABLE TREATMENT
            (
             TREATMENT_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            DOCTOR_ID NUMBER(10) NOT NULL,
            PATIENT_ID NUMBER(10) NOT NULL,
            TREATMENT_TYPE VARCHAR2(30) NOT NULL,
            CONSTRAINT TREATMENT_ID PRIMARY KEY (TREATMENT_ID),
            CONSTRAINT TREATMENT_FK_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
            CONSTRAINT TREATMENT_FK_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
    )
    ')]';
    
       EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('BILL','CREATE TABLE BILL
            (
             BILL_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
             TREATMENT_ID NUMBER(10) NOT NULL,
             HOSPITAL_ID NUMBER(10) NOT NULL,
             BILL_DATE DATE NOT NULL,
            AMOUNT NUMBER(10) NOT NULL,
            CONSTRAINT BILL_ID PRIMARY KEY (BILL_ID),
            CONSTRAINT BILL_FK_TREATMENT FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID),
            CONSTRAINT BILL_FK_HOSPITAL FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
        )
        ')]';
        
        
        
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('CLAIM','CREATE TABLE CLAIM
            (
            CLAIM_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
            POLICY_NO NUMBER(10) NOT NULL,
            BILL_ID NUMBER(10) NOT NULL,
            CLAIM_AMOUNT NUMBER(10) NOT NULL,
            CLAIM_DATE DATE NOT NULL,
            STATUS VARCHAR2(10) NOT NULL,
            CONSTRAINT CLAIM_ID PRIMARY KEY (CLAIM_ID),
            CONSTRAINT CLAIM_FK_POLICY FOREIGN KEY (POLICY_NO) REFERENCES POLICY(POLICY_NO),
            CONSTRAINT CLAIM_FK_BILL FOREIGN KEY (BILL_ID) REFERENCES BILL(BILL_ID)
              
             )
       ')]';

        
 
 
        
   
   
    
    
         
    END IF;
    EXCEPTION
  WHEN CHECK_CONSTRAINT_VIOLATED THEN  -- catch the ORA-02290 exception
   raise_application_error(-20000, 'Failed to update');
    WHEN OTHERS THEN                     -- catch all other exceptions
    DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || SQLCODE ||
                         ' : ' || SQLERRM);
      
END;
/

DECLARE
        CURSOR config_table_cur
      IS
        SELECT 
            *
        FROM 
            config_table;
            
        tab_name varchar2(50);
        tab_def varchar2(3000);
        row_count number(10):= 0;
    BEGIN
      FOR i IN config_table_cur
      LOOP
          tab_name:= i.table_name;
          tab_def:= i.table_def;
          
          DBMS_OUTPUT.PUT_LINE('--------------------------');
    
          SELECT count(*) into row_count FROM user_tables where table_name = tab_name;
           IF(row_count > 0)
            THEN
                DBMS_OUTPUT.PUT_LINE('TABLE '|| tab_name || ' ALREADY EXISTS');
            ELSE
                DBMS_OUTPUT.PUT_LINE('--------------------------');  
                EXECUTE IMMEDIATE tab_def;
                dbms_output.put_line( 'TABLE '|| tab_name || ' CREATED SUCCESSFULLY!' );
             END IF;
      END LOOP;
      dbms_output.put_line( 'ALL TABLES CREATED');
END;
/ 



CREATE OR REPLACE PROCEDURE ADD_INSURANCE_COMPANY(COMPANY_NAME IN VARCHAR2, PHONE_NO IN NUMBER, STREET IN VARCHAR2, CITY IN VARCHAR2, STATE IN VARCHAR2, ZIPCODE IN VARCHAR2)
IS
BEGIN
INSERT INTO INSURANCE_COMPANY(COMPANY_NAME, PHONE_NO, STREET, CITY, STATE, ZIPCODE) VALUES (COMPANY_NAME, PHONE_NO, STREET, CITY, STATE, ZIPCODE);
  
END ADD_INSURANCE_COMPANY;
/
CREATE OR REPLACE PROCEDURE ADD_AGENT(COMPANY_ID IN NUMBER,FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2, PHONE IN NUMBER, EMAIL IN VARCHAR2)
IS 
BEGIN
INSERT INTO AGENT(COMPANY_ID,FIRST_NAME, LAST_NAME, PHONE, EMAIL) VALUES(COMPANY_ID,FIRST_NAME, LAST_NAME, PHONE, EMAIL);

END ADD_AGENT;
/ 
--ADD_CORPORATE_CLIENTS
CREATE OR REPLACE PROCEDURE ADD_CORPORATE_CLIENTS(COMPANY_ID IN NUMBER, CLIENT_NAME IN VARCHAR2, TOTAL_EMPLOYEES IN NUMBER)
IS 
BEGIN
INSERT INTO CORPORATE_CLIENTS(COMPANY_ID, CLIENT_NAME, TOTAL_EMPLOYEES) VALUES(COMPANY_ID, CLIENT_NAME, TOTAL_EMPLOYEES);

END ADD_CORPORATE_CLIENTS;
/ 
--ADD_CUSTOMER
CREATE OR REPLACE PROCEDURE ADD_CUSTOMER(AGENT_ID IN NUMBER, CLIENT_ID IN NUMBER, FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2, SSN IN NUMBER, EMAIL IN VARCHAR2, STREET_NAME IN VARCHAR2, CITY IN VARCHAR2, STATE IN VARCHAR2, ZIPCODE IN NUMBER)
IS 
BEGIN
INSERT INTO CUSTOMER(AGENT_ID, CLIENT_ID, FIRST_NAME, LAST_NAME, SSN, EMAIL, STREET_NAME, CITY, STATE, ZIPCODE) VALUES(AGENT_ID, CLIENT_ID, FIRST_NAME, LAST_NAME, SSN, EMAIL, STREET_NAME, CITY, STATE, ZIPCODE);
Exception
when Others then 
DBMS_OUTPUT.PUT_LINE('Something else went wrong - ' || 
                         ' : ' || SQLERRM);
END ADD_CUSTOMER;
/ 
--POLICY CATALOGUE
CREATE OR REPLACE PROCEDURE ADD_POLICY_CATALOGUE (COMPANY_ID IN NUMBER, PREMIUM IN VARCHAR2, COPAY IN NUMBER, TENURE IN NUMBER)
IS
BEGIN
INSERT INTO POLICY_CATALOGUE(COMPANY_ID, PREMIUM, COPAY, TENURE) VALUES (COMPANY_ID, PREMIUM, COPAY, TENURE);
 
END ADD_POLICY_CATALOGUE;
/
--ADD_POLICY

CREATE OR REPLACE PROCEDURE ADD_POLICY (CUSTOMER_ID IN NUMBER, POLICY_ID IN NUMBER , POLICY_EXPIRY_DATE IN DATE)
IS
BEGIN
  INSERT INTO POLICY(CUSTOMER_ID, POLICY_ID,POLICY_EXPIRY_DATE) VALUES(CUSTOMER_ID, POLICY_ID,POLICY_EXPIRY_DATE);
  
END ADD_POLICY;
/
--ADD_PATIENT

CREATE OR REPLACE PROCEDURE ADD_PATIENT(CUSTOMER_ID IN NUMBER, FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2, RELATIONSHIP IN VARCHAR2, PATIENT_DOB IN VARCHAR2)
IS

BEGIN
INSERT INTO PATIENT(CUSTOMER_ID, FIRST_NAME, LAST_NAME, RELATIONSHIP, PATIENT_DOB) VALUES (CUSTOMER_ID, FIRST_NAME, LAST_NAME, RELATIONSHIP, PATIENT_DOB);

END ADD_PATIENT;
/
--ADD_HOSPITAL
CREATE OR REPLACE PROCEDURE ADD_HOSPITAL(HOSPITAL_NAME IN VARCHAR2, ADDRESS IN VARCHAR2, CITY IN VARCHAR2, STATE IN VARCHAR2, ZIPCODE IN NUMBER)
IS 
BEGIN
INSERT INTO HOSPITAL(HOSPITAL_NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES(HOSPITAL_NAME, ADDRESS, CITY, STATE, ZIPCODE);

END ADD_HOSPITAL;
/ 
--ADD_DOCTOR
CREATE OR REPLACE PROCEDURE ADD_DOCTOR(HOSPITAL_ID IN NUMBER, FIRST_NAME IN VARCHAR2, LAST_NAME IN VARCHAR2, DEPARTMENT IN VARCHAR2)
IS 
BEGIN
INSERT INTO DOCTOR(HOSPITAL_ID, FIRST_NAME, LAST_NAME, DEPARTMENT) VALUES(HOSPITAL_ID, FIRST_NAME, LAST_NAME, DEPARTMENT);

END ADD_DOCTOR;
/ 
--TREATMENT
CREATE OR REPLACE PROCEDURE ADD_TREATMENT( DOCTOR_ID IN NUMBER, PATIENT_ID IN NUMBER, TREATMENT_TYPE IN VARCHAR2)
IS
BEGIN
INSERT INTO TREATMENT(DOCTOR_ID, PATIENT_ID, TREATMENT_TYPE) VALUES (DOCTOR_ID, PATIENT_ID, TREATMENT_TYPE);
  
END ADD_TREATMENT;
/
--ADD_BILL
CREATE OR REPLACE PROCEDURE ADD_BILL(TREATMENT_ID IN NUMBER,HOSPITAL_ID IN NUMBER, BILL_DATE IN DATE, AMOUNT IN NUMBER)
IS 
BEGIN
INSERT INTO BILL(TREATMENT_ID,HOSPITAL_ID, BILL_DATE, AMOUNT) VALUES(TREATMENT_ID,HOSPITAL_ID, BILL_DATE, AMOUNT);

END ADD_BILL;
/ 
CREATE OR REPLACE PROCEDURE ADD_CLAIM(POLICY_NO IN NUMBER,BILL_ID IN NUMBER, CLAIM_AMOUNT IN NUMBER, CLAIM_DATE IN DATE, STATUS IN VARCHAR2)
IS 
BEGIN
INSERT INTO CLAIM(POLICY_NO,BILL_ID, CLAIM_AMOUNT, CLAIM_DATE, STATUS) VALUES(POLICY_NO,BILL_ID, CLAIM_AMOUNT, CLAIM_DATE, STATUS);

END ADD_CLAIM;
/

INSERT INTO  INSURANCE_COMPANY(COMPANY_NAME,PHONE_NO,STREET,CITY,STATE,ZIPCODE)VALUES('NUINSURANCE',6176524464,'170 PARKER HILL AVE','BOSTON','MA','02120');



EXECUTE ADD_AGENT(1,'RISHI','FIRKE',8503988836,'RISHI@GMAIL.COM');
EXECUTE ADD_AGENT(1,'ANIL','DESAI',8513998847,'ANIL@GMAIL.COM');
EXECUTE ADD_AGENT(1,'RUTUJA','GHOGARE',8583988833,'RUTUJA@GMAIL.COM');


EXECUTE ADD_CORPORATE_CLIENTS(1,'JOHN.CO', 400);
EXECUTE ADD_CORPORATE_CLIENTS(1,'WALGREEN', 500);
EXECUTE ADD_CORPORATE_CLIENTS(1,'GOOGLE', 4500);
EXECUTE ADD_CORPORATE_CLIENTS(1,'FACEBOOK', 5000);
EXECUTE ADD_CORPORATE_CLIENTS(1,'CCC', 1800);
EXECUTE ADD_CORPORATE_CLIENTS(1,'CITI', 2500);




EXECUTE ADD_POLICY_CATALOGUE(1,'1000', 75, 24);
EXECUTE ADD_POLICY_CATALOGUE(1,'2000', 20, 12);
EXECUTE ADD_POLICY_CATALOGUE(1,'2200', 20, 60);
EXECUTE ADD_POLICY_CATALOGUE(1,'2600', 100, 48);
EXECUTE ADD_POLICY_CATALOGUE(1,'3000', 50, 18);

EXECUTE ADD_CUSTOMER(1, NULL, 'JOHN', 'MICH', '123456789', 'JOHN.MICH@GMAI.COM', 'MT PLEASENT AVE', 'BOSTON', ' MA', 1234);
EXECUTE ADD_CUSTOMER(1, NULL, 'JACK', 'ROY', '786543219', 'JACK.ROY@GMAI.COM', 'HUNTINGTON AVE', 'BOSTON', ' MA', 1432);
EXECUTE ADD_CUSTOMER(2, NULL, 'BOB', 'HARRIS', '987654321', 'BOB.HARRIS@GMAI.COM', 'ROAD ISLAND', 'HOUSTON', ' TEXAS', 9876);
EXECUTE ADD_CUSTOMER(2, NULL, 'SAHIL', 'JOSHI', '567345298', 'SAHIL.JOSHI@GMAI.COM', 'BACK BAY', 'DALLAS', ' TEXAS', 6785);
EXECUTE ADD_CUSTOMER(3, NULL, 'TINA', 'RAUT', '457689326', 'TINA.RAUT@GMAIL.COM', 'MAIN ROAD', 'SAN FRANSISCO', ' CAL', 6754);
EXECUTE ADD_CUSTOMER(3, NULL, 'SIMRAN', 'NAGPURKAR', '678453217', 'SIMRAN.NAGPURKAR@GMAL.COM', 'ROXBURY', 'BOSTON', ' MA', 9821);
EXECUTE ADD_CUSTOMER(NULL, 1, 'SITA', 'PATEL', '564321987', 'SITA.PATEL@GMAIL.COM', 'SYRACUSE', 'NEW YORK', ' NY', 3215);
EXECUTE ADD_CUSTOMER(NULL, 1, 'RAJ', 'DEV', '238764598', 'RAJ.DEV@GMAIL.COM', 'TIMES SQUARE', 'NEW YORK', ' NY', 9123);
EXECUTE ADD_CUSTOMER(NULL, 2, 'SWAROOPA', 'LAXMI', '345678921', 'RAJ.DEV@GMAIL.COM', 'WASHINGTON AVENUE', 'CHELSI', 'DENVER', 2156);
EXECUTE ADD_CUSTOMER(NULL, 2, 'RAMESH', 'KUMAR', '532987654', 'RAMESH.KUMAR@GMAIL.COM', 'HIGH STREET', 'BRIGHTON', 'CALIFORNIA', 1256);
EXECUTE ADD_CUSTOMER(NULL, 3, 'NITA', 'SHAIKH', '765432198', 'NITA.SHAIKH@GMAIL.COM', 'LOWER BAY', 'MANHATTAN', 'NEW YORK', 9876);
EXECUTE ADD_CUSTOMER(NULL, 4, 'RASIKA', 'JOSHI', '234987654', 'RASIKA.JOSHI@GMAIL.COM', 'MT HILL AVE', 'SYRACUSE', 'NEW YORK', 2345);
EXECUTE ADD_CUSTOMER(NULL, 5, 'TEJASWINI', 'NANDALA', '567894321', 'TEJASWINI.NANDALA@GMAIL.COM', 'TERMONT ST', 'BOSTON', 'MA', 3295);
EXECUTE ADD_CUSTOMER(NULL, 6, 'TARUN', 'MOVVA', '234567896', 'TARUN.MOVVA@GMAIL.COM', 'S POINT DRIVE', 'DORCHESTER', 'CHICAGO', 8765);
EXECUTE ADD_CUSTOMER(NULL, 6, 'SAMPADA', 'DHOLE', '678905432', 'SAMPADA.DHOLE@GMAIL.COM', 'CLINGTON ST', 'TEXAS', 'AUSTIN', 1446);
EXECUTE ADD_CUSTOMER(NULL, 6, 'KAVITA', 'DAMLE', '123459876', 'KAVITA.DAMLE@GMAIL.COM', '59 S AVE', 'DEDHAM', 'CALIFORNIA', 2130);

--rutuja

EXECUTE ADD_CUSTOMER (4, NULL, 'Margaretha',	'Clowser',	'538808054,'	'mclowser0@geocities.com',	'Sundown', 	'Burbank',	'California', 	91505);
EXECUTE ADD_CUSTOMER (5, NULL, 'Maxim','Hankins',	'211126834',	'mhankins1@google.ca',	'Monica',	'Chicago',	'Illinois',	60604);
EXECUTE ADD_CUSTOMER (5, NULL, 'Josias',	'Shorter',	'122892869',	'jshorter2@salon.com',	'Hazelcrest',	'Corona',	'California',	92883
EXECUTE ADD_CUSTOMER (6, NULL, 'Forester',	'Skevington',	'427333906',	'fskevington3@twitter.com',	'Anzinger',	'Dallas',	'Texas',	75387
EXECUTE ADD_CUSTOMER (6, NULL, 'Humfrey',	'Fryatt',	'717914757',	'hfryatt4@amazonaws.com',	'Sachtjen',	'San Antonio',	'Texas',	78285
EXECUTE ADD_CUSTOMER (7, NULL, 'Upton',	'Kadwallider',	'781047479',	'ukadwallider5@cnn.com',	'Sugar',	'Columbus',	'Georgia',	31998
EXECUTE ADD_CUSTOMER (7, NULL, 'Garwin',	'Handsheart',	'672933292',	'ghandsheart6@toplist.cz',	'Monument',	'Anchorage',	'Alaska'	99507
EXECUTE ADD_CUSTOMER (8, NULL, 'Harri',	'Wrightson',	'375325730',	'hwrightson7@a8.net	Hooker',	'Davenport',	'Iowa',	52804
EXECUTE ADD_CUSTOMER (8, NULL, 'Marlie',	'Caldicot',	'275708699',	'mcaldicot8@google.nl',	'Eagle Crest',	'Springfield',	'Massachusetts',	1114
EXECUTE ADD_CUSTOMER (NULL, 7, 'Tabbie',	'Foulger', '712460432',	'tfoulger9@chronoengine.com',	'Gina',	'New Haven',	'Connecticut'	6510
EXECUTE ADD_CUSTOMER (NULL, 7, 'Charmion',	'McMenamie',	'628663147',	'cmcmenamiea@istockphoto.com',	'Homewood',	'Petaluma',	'California'	94975
EXECUTE ADD_CUSTOMER (NULL, 8, 'Benny',	'Lundbeck',	'699549850',	'blundbeckb@facebook.com', 'Atwood',	'El Paso',	'Texas',	88535
EXECUTE ADD_CUSTOMER (NULL, 8, 'Cori',	'Baert',	'372622369',	'cbaertc@gizmodo.com',	'Southridge',	'Henderson',	'Nevada',	89074
EXECUTE ADD_CUSTOMER (NULL, 9, 'Lolly',	'Caskie',	'258562834',	'lcaskied@nydailynews.com',	'Hayes',	'Chicago',	'Illinois',	60681
EXECUTE ADD_CUSTOMER (NULL, 9, 'Javier',	'Tedman',	'119435312',	'jtedmane@quantcast.com',	'Clemons',	'Austin',	'Texas',	78764
EXECUTE ADD_CUSTOMER (NULL, 10, 'Alfons',	'Rubinovici',	'233217820',	'arubinovicif@desdev.cn',	'Scoville',	'Seattle',	'Washington',	98121
EXECUTE ADD_CUSTOMER (NULL, 10, 'Amalie',	'Stodhart',	'559827431',	'astodhartg@hhs.gov',	'Killdeer',	'Las Vegas',	'Nevada',	89166
EXECUTE ADD_CUSTOMER (1, NULL, 'Barty',	'Sibbe',	'494999506',	'bsibbeh@paginegialle.it',	'Sachtjen',	'Anniston',	'Alabama',	36205
EXECUTE ADD_CUSTOMER (1, NULL, 'Jarrod',	'Kinlock',	'428104072',	'jkinlocki@merriam-webster.com',	'Pierstorff',	'Topeka',	'Kansas',	66606
EXECUTE ADD_CUSTOMER (2, NULL, 'Louisette',	'Tully',	'124748400',	'ltullyj@walmart.com',	'New Castle',	'Salt Lake City',	'Utah'	84199
EXECUTE ADD_CUSTOMER (2, NULL, 'Sophronia',	'Arrighi',	'435855473',	'sarrighik@netvibes.com',	'Huxley',	'Yonkers',	'New York',	10705
EXECUTE ADD_CUSTOMER (3, NULL, 'Petey',	'Turpin',	'580776498',	'pturpinl@cdbaby.com',	'Forest',	'Bronx',	'New York',	10469
EXECUTE ADD_CUSTOMER (3, NULL, 'Haily',	'Nestor',	'382855099',	'hnestorm@ning.com',	'Hovde',	'Rochester',	'New York',	14614
EXECUTE ADD_CUSTOMER (4, NULL, 'Jimmy',	'Algie',	'316029449',	'jalgien@quantcast.com',	'Saint Paul',	'Birmingham',	'Alabama',	35215
EXECUTE ADD_CUSTOMER (4, NULL, 'Esmeralda',	'Luscott',	'203387996',	'eluscotto@addthis.com',	'Moland',	'Las Vegas',	'Nevada',	89130
EXECUTE ADD_CUSTOMER (NULL, 1, 'Binnie',	'Imesson',	'465350456',	'bimessonp@people.com.cn',	'Elgar',	'Portland',	'Oregon',	97240
EXECUTE ADD_CUSTOMER (NULL, 1, 'Guillema',	'Duberry',	'179975847',	'gduberryq@ovh.net',	'Graedel',	'Wilkes Barre',	'Pennsylvania',	18706
EXECUTE ADD_CUSTOMER (NULL, 2, 'Batsheva',	'Balaisot',	'765477938',	'bbalaisotr@live.com',	'Sachs',	'Baton Rouge',	'Louisiana',	70820
EXECUTE ADD_CUSTOMER (NULL, 2, 'Giorgia',	'Elwell',	'416136336', 	'gelwells@usda.gov',	'Sunnyside',	'Birmingham',	'Alabama',	35242
EXECUTE ADD_CUSTOMER (NULL, 3, 'Micki',	'Sidlow',	'365938640',	'msidlowt@prweb.com',	'Transport',	'Santa Fe	New', 'Mexico',	87505
EXECUTE ADD_CUSTOMER (NULL, 3, 'Dov',	'Agates',	'227683124',	'dagatesu@jimdo.com', 'Sherman',	'Greensboro',	'North Carolina',	27455
EXECUTE ADD_CUSTOMER (NULL, 4, 'Carolynn',	'Bartul',	'548926769',	'cbartulv@ibm.com',	'Hauk',	'Fort Myers',	'Florida',	33913
EXECUTE ADD_CUSTOMER (NULL, 4, 'Dulcy',	'Quickfall',	'562379103',	'dquickfallw@si.edu',	'Surrey',	'Atlanta',	'Georgia',	31136
EXECUTE ADD_CUSTOMER (NULL, 5, 'Baxy',	'Entwhistle',	'553083113',	'bentwhistlex@imdb.com',	'Hanson',	'Fargo',	'North Dakota',	58106
EXECUTE ADD_CUSTOMER (NULL, 5, 'Mala',	'Itzkov',	'371202753',	'mitzkovy@columbia.edu',	'Leroy',	'Bronx',	'New York',	10474
EXECUTE ADD_CUSTOMER (8, NULL, 'Northrup',	'Hallums',	'635154575',	'nhallumsz@quantcast.com',	'Forest Run',	'Tulsa',	'Oklahoma',	74156
EXECUTE ADD_CUSTOMER (8, NULL, 'Twila',	'Aldhous',	'662278422'	'taldhous10@virginia.edu',	'Mitchell Grand', 'Rapids',	'Michigan',	49505
EXECUTE ADD_CUSTOMER (7, NULL, 'Bobbee',	'Rubartelli',	'484429114',	'brubartelli11@utexas.edu',	'Arapahoe',	'Ogden',	'Utah',	84403
EXECUTE ADD_CUSTOMER (7, NULL, 'Agustin',	'Lindblad',	'591018809',	'alindblad12@businesswire.com',	'Waxwing',	'Palatine',	'Illinois',	60078
EXECUTE ADD_CUSTOMER (6, NULL, 'Stanly',	'Cornehl',	'223383704',	'scornehl13@smh.com.au',	'Forest Dale',	'Largo',	'Florida',	34643
EXECUTE ADD_CUSTOMER (6, NULL, 'Lombard',	'Hedling',	'232097297',	'lhedling14@uiuc.edu',	'Monument',	'Metairie',	'Louisiana',	70005
EXECUTE ADD_CUSTOMER (5, NULL, 'Fran',	'Seabrook',	'220946247',	'fseabrook15@addtoany.com',	'Armistice',	'Charleston',	'West Virginia',	25336
EXECUTE ADD_CUSTOMER (5, NULL, 'Editha',	'Agass',	'814667373',	'eagass16@mlb.com',	'Express',	'Montgomery',	'Alabama',	36125
EXECUTE ADD_CUSTOMER (4, NULL, 'Salvidor',	'Beaten',	'835436597',	'sbeaten17@mtv.com',	'Fuller',	'Tucson',	'Arizona',	85754
EXECUTE ADD_CUSTOMER (4, NULL, 'Saleem',	'Clemenzi',	'763183920',	'sclemenzi18@theatlantic.com',	'Main',	'Tulsa',	'Oklahoma',	74141
EXECUTE ADD_CUSTOMER (NULL, 10, 'Rosita',	'Hillett',	'277551533', 'rhillett19@earthlink.net',	'Quincy',	'Beaumont',	'Texas',	77705
EXECUTE ADD_CUSTOMER (NULL, 10, 'Othilie',	'Gelardi',	'327953146',	'ogelardi1a@microsoft.com',	'Norway', 'Maple',	'Sacramento',	'California',	95865
EXECUTE ADD_CUSTOMER (NULL, 10, 'Stu',	'Allnatt',	'650161003',	'sallnatt1b@free.fr',	'Erie',	'Denver',	'Colorado',	80299
EXECUTE ADD_CUSTOMER (NULL, 9, 'Darlleen',	'Redhills',	'328301870',	'dredhills1c@forbes.com',	'Blue Bill Park',	'Akron',	'Ohio',	44393
EXECUTE ADD_CUSTOMER (NULL, 9, 'Clarice',	'Wooffitt',	'663435326',	'cwooffitt1d@bbb.org',	'Butternut',	'Miami',	'Florida',	33142
EXECUTE ADD_CUSTOMER (NULL, 8, 'Giacomo',	'Robken',	'898338775',	'grobken1e@flavors.me',	'Bluestem',	'El Paso',	'Texas',	79989
EXECUTE ADD_CUSTOMER (NULL, 8, 'Clio',	'Ashe',	'500566431',	'cashe1f@oakley.com',	'Aberg',	'Charlotte',	'North Carolina',	28205
EXECUTE ADD_CUSTOMER (NULL, 7, 'Leonore',	'Spellman',	'801477902',	'lspellman1g@t-online.de',	'Oakridge',	'Denver',	'Colorado',	80217
EXECUTE ADD_CUSTOMER (NULL, 7, 'Estele',	'Pentony',	'474168842',	'epentony1h@furl.net',	'Rockefeller',	'Washington',	'District of Columbia',	20299
EXECUTE ADD_CUSTOMER (NULL, 6, 'Alex',	'Balshen',	'528644427',	'abalshen1i@umich.edu',	'Arizona',	'Portsmouth',	'New Hampshire',	214
EXECUTE ADD_CUSTOMER (NULL, 6, 'Sawyere',	'Faireclough',	'877290219',	'sfaireclough1j@squidoo.com',	'Eastlawn',	'Raleigh',	'North Carolina',	27610
EXECUTE ADD_CUSTOMER (3, NULL, 'Clive',	'Barok',	'868836094',	'cbarok1k@techcrunch.com',	'Northport',	'Long Beach',	'California',	90810
EXECUTE ADD_CUSTOMER (3, NULL, 'Kara',	'Mityushin',	'843185708',	'kmityushin1l@scribd.com',	'Vermont',	'Charlotte',	'North Carolina',	28284
EXECUTE ADD_CUSTOMER (1, NULL, 'Gordy',	'Capnerhurst',	'881076214',	'gcapnerhurst1m@weebly.com',	'Annamark',	'Roanoke',	'Virginia',	24004
EXECUTE ADD_CUSTOMER (1, NULL, 'Mateo',	'Drakeford',	'116863232',	'mdrakeford1n@sina.com.cn',	'Quincy',	'Indianapolis',	'Indiana',	46278
EXECUTE ADD_CUSTOMER (2, NULL, 'Pedro',	'Grundle',	'525346281',	'pgrundle1o@addtoany.com',	'Almo',	'Phoenix',	'Arizona',	85035
EXECUTE ADD_CUSTOMER (2, NULL, 'Gennifer',	'Jessope',	'273386468',	'gjessope1p@networkadvertising.org',	'Lerdahl',	'Honolulu',	'Hawaii',	96835
EXECUTE ADD_CUSTOMER (3, NULL, 'Fleming',	'Jancic',	'298356675',	'fjancic1q@europa.eu',	'Maywood',	'Grand Junction',	'Colorado',	81505
EXECUTE ADD_CUSTOMER (4, NULL, 'Patrice',	'Stroband',	'339699419',	'pstroband1r@rakuten.co.jp',	'Kedzie',	'Knoxville',	'Tennessee',	37931
EXECUTE ADD_CUSTOMER (4, NULL, 'Terencio',	'Canaan',	'27364-7011',	'tcanaan1s@shop-pro.jp',	'Kings',	'Sioux Falls',	'South Dakota',	57193
EXECUTE ADD_CUSTOMER (5, NULL, 'Gae',	'Curnick',	'430370126',	'gcurnick1t@trellian.com',	'Maryland',	'Young America',	'Minnesota',	55551
EXECUTE ADD_CUSTOMER (5, NULL, 'Verene',	'Vescovo',	'139297762',	'vvescovo1u@statcounter.com',	'Rigney',	'Pueblo',	'Colorado',	81005
EXECUTE ADD_CUSTOMER (NULL, 1, 'Kala',	'Pilling',	'702676051',	'kpilling1v@usatoday.com',	'Warrior',	'Canton',	'Ohio',	44760
EXECUTE ADD_CUSTOMER (NULL, 1, 'Page',	'Dulwich',	'596572466',	'pdulwich1w@sun.com',	'Iowa',	'Reading',	'Pennsylvania',	19605
EXECUTE ADD_CUSTOMER (NULL, 2, 'Kiah',	'Osipov',	'443965609',	'kosipov1x@abc.net.au',	'American',	'Charleston',	'West Virginia',	25326
EXECUTE ADD_CUSTOMER (NULL, 2, 'Ola',	'Calderbank',	'615342903',	'ocalderbank1y@soundcloud.com',	'Jay',	'Miami',	'Florida',	33245
EXECUTE ADD_CUSTOMER (NULL, 3, 'Meredith',	'Bollis',	'202165919',	'mbollis1z@naver.com',	'Superior',	'Buffalo',	'New York',	14233
EXECUTE ADD_CUSTOMER (NULL, 3, 'Cloris',	'Wegman',	'292692144',	'cwegman20@prnewswire.com',	'Lake View',	'Springfield',	'Massachusetts',	1152
EXECUTE ADD_CUSTOMER (NULL, 3, 'Georgie',	'Ruane',	'610747984',	'gruane21@livejournal.com',	'Merrick',	'Minneapolis',	'Minnesota',	55436
EXECUTE ADD_CUSTOMER (NULL, 6, 'Frannie',	'Loody',	'139690550',	'floody22@bbb.org',	'Lotheville',	'Vancouver',	'Washington',	98664
EXECUTE ADD_CUSTOMER (NULL, 6, 'Filbert',	'Scimone',	'624043180',	'fscimone23@1und1.de',	'Farwell',	'Fargo',	'North Dakota',	58122
EXECUTE ADD_CUSTOMER (NULL, 7, 'Samaria',	'Sawney',	'661591649',	'ssawney24@senate.gov',	'Surrey',	'Columbus',	'Mississippi',	39705
EXECUTE ADD_CUSTOMER (NULL, 7, 'Alphonso',	'Ouslem',	'611106517',	'aouslem25@51.la',	'Eagan',	'Washington',	'District of Columbia',	20244
EXECUTE ADD_CUSTOMER (4, NULL, 'Burlie',	'Chasmer',	'301490424',	'bchasmer26@cdbaby.com',	'Melvin',	'Mesa',	'Arizona',	85210
EXECUTE ADD_CUSTOMER (4, NULL, 'Flossie',	'Phipard-Shears',	'344194430',	'fphipardshears27@e-recht24.de',	'Spenser',	'Springfield',	'Massachusetts',	1105
EXECUTE ADD_CUSTOMER (5, NULL, 'Dulciana',	'Aslin',	'252208952',	'daslin28@tinyurl.com',	'Texas',	'Englewood',	'Colorado',	80150
EXECUTE ADD_CUSTOMER (5, NULL, 'Bertrand',	'McElwee',	'815233118',	'bmcelwee29@geocities.jp',	'Porter',	'New York City',	'New York',	10115
EXECUTE ADD_CUSTOMER (6, NULL, 'Say',	'Vardie',	'701138104',	'svardie2a@nps.gov',	'Sutherland',	'Huntington',	'West Virginia',	25775
EXECUTE ADD_CUSTOMER (6, NULL, 'Errol',	'Le Page',	'382547532',	'elepage2b@reddit.com',	'Donald'	'Reno',	'Nevada',	89519
EXECUTE ADD_CUSTOMER (7, NULL, 'Pierson',	'Mauchlen',	'649547860',	'pmauchlen2c@cdbaby.com',	'Calypso',	'Silver Spring',	'Maryland',	20904
EXECUTE ADD_CUSTOMER (7, NULL, 'Ax',	'Whitmore',	'299275578',	'awhitmore2d@webmd.com',	'Fairfield',	'El Paso',	'Texas',	79916
EXECUTE ADD_CUSTOMER (7, NULL, 'Devy',	'Mallock',	'721425350',	'dmallock2e@elegantthemes.com',	'Nobel',	'Tyler',	'Texas',	75799
EXECUTE ADD_CUSTOMER (8, NULL, 'Guendolen',	'Biggen',	'773736614',	'gbiggen2f@soup.io',	'Green Ridge',	'New Haven',	'Connecticut',	6533
EXECUTE ADD_CUSTOMER (8, NULL, 'Thorndike',	'Bessey',	'489503540',	'tbessey2g@pinterest.com',	'Briar Crest',	'Oceanside',	'California',	92056
EXECUTE ADD_CUSTOMER (NULL, 10, 'Aggie',	'Dagon',	'326586945',	'adagon2h@thetimes.co.uk',	'Artisan',	'Chico',	'California',	95973
EXECUTE ADD_CUSTOMER (NULL, 10, 'Shelbi',	'Giannini',	'761460811',	'sgiannini2i@webnode.com',	'Northview',	'Amarillo',	'Texas',	79188
EXECUTE ADD_CUSTOMER (NULL, 9, 'Gil',	'Chucks',	'653425113',	'gchucks2j@bbb.org',	'Warbler',	'Dallas',	'Texas',	75387
EXECUTE ADD_CUSTOMER (NULL, 9, 'Suzy',	'Spender',	'265402808',	'sspender2k@tinypic.com',	'Del Mar',	'Birmingham',	'Alabama',	35254
EXECUTE ADD_CUSTOMER (NULL, 9, 'Nedda',	'Dunton',	'556849252',	'ndunton2l@mediafire.com',	'Blue Bill Park',	'Washington',	'District of Columbia',	20535
EXECUTE ADD_CUSTOMER (NULL, 8, 'Kay',	'Side',	'103902113',	'kside2m@biglobe.ne.jp',	'Amoth',	'Canton',	'Ohio',	44760
EXECUTE ADD_CUSTOMER (NULL, 8, 'Kirstin',	'Gravenell',	'796851355',	'kgravenell2n@ocn.ne.jp',	'Roth',	'Reno',	'Nevada',	89550
EXECUTE ADD_CUSTOMER (NULL, 3, 'Heinrik',	'Freak',	'719568032',	'hfreak2o@netscape.com',	'Hoffman',	'Lansing',	'Michigan',	48901
EXECUTE ADD_CUSTOMER (NULL, 3, 'Erl',	'Janc',	'744669687',	'ejanc2p@omniture.com',	'Walton',	'Philadelphia',	'Pennsylvania',	19115
EXECUTE ADD_CUSTOMER (8, NULL, 'Ximenez',	'Baraclough',	'152036035',	'xbaraclough2q@baidu.com',	'Warner',	'Toledo',	'Ohio',	43666
EXECUTE ADD_CUSTOMER (8, NULL, 'Cazzie',	'Clist',	'417986219',	'cclist2r@yandex.ru',	'Village',	'Portland',	'Oregon',	97206
EXECUTE ADD_CUSTOMER (7, NULL, 'Yasmeen',	'Dettmar',	'894625716',	'ydettmar2s@latimes.com',	'Loftsgordon',	'Charlotte',	'North Carolina',	28220
EXECUTE ADD_CUSTOMER (7, NULL, 'Kenyon',	'Kestin',	'497741925',	'kkestin2t@phoca.cz',	'Loftsgordon',	'Petaluma',	'California',	94975
EXECUTE ADD_CUSTOMER (1, NULL, 'Carolyn	O', 'Cullen',	'155048920',	'cocullen2u@tinyurl.com',	'Esker',	'Mobile',	'Alabama',	36670
EXECUTE ADD_CUSTOMER (1, NULL, 'Shaylyn',	'Songest',	'354272519',	'ssongest2v@army.mil',	'Eastwood',	'Mesa',	'Arizona',	85210
EXECUTE ADD_CUSTOMER (1, NULL, 'Norrie',	'Bonifazio',	'615443373',	'nbonifazio2w@gov.uk',	'Leroy',	'Huntsville',	'Alabama',	35810
EXECUTE ADD_CUSTOMER (2, NULL, 'Frasquito',	'Moulster'	'652859785',	'fmoulster2x@networksolutions.com',	'Northwestern',	'Houston',	'Texas',	77070
EXECUTE ADD_CUSTOMER (2, NULL, 'Culley',	'Quincee',	'233494759',	'cquincee2y@dailymotion.com',	'Victoria',	'New York City',	'New York',	10105
EXECUTE ADD_CUSTOMER (4, NULL, 'Sapphire',	'Tregona',	'626335148',	'stregona2z@yahoo.co.jp',	'Johnson',	'Apache Junction',	'Arizona',	85219
EXECUTE ADD_CUSTOMER (4, NULL, 'Rafa',	'Prettyjohns'	'725233323',	'rprettyjohns30@ning.com',	'Morrow',	'Tyler',	'Texas',	75799
EXECUTE ADD_CUSTOMER (NULL, 10, 'Kilian',	'Brugger',	'704469586',	'kbrugger31@uol.com.br',	'Charing Cross',	'Jamaica',	'New York',	11431
EXECUTE ADD_CUSTOMER (NULL, 10, 'Ker',	'Wiles',	'134953394',	'kwiles32@rediff.com',	'Glacier Hill',	'Fort Worth',	'Texas',	76110
EXECUTE ADD_CUSTOMER (NULL, 9, 'Ines',	'Goulter',	'680259443',	'igoulter33@prweb.com',	'Sycamore',	'Milwaukee',	'Wisconsin',	53210
EXECUTE ADD_CUSTOMER (NULL, 9, 'Laura',	'Scarisbrick',	'159582274',	'lscarisbrick34@blogger.com',	'Killdeer',	'San Jose',	'California',	95113
EXECUTE ADD_CUSTOMER (NULL, 8, 'Ibrahim',	'Winspurr',	'580993549',	'iwinspurr35@ed.gov',	'Rutledge',	'Buffalo',	'New York',	14225
EXECUTE ADD_CUSTOMER (NULL, 7, 'Sela',	'Knappett',	'678903781',	'sknappett36@ted.com',	'Talisman',	'Washington',	'District of Columbia',	20268
EXECUTE ADD_CUSTOMER (NULL, 7, 'Rad',	'Sybbe',	'419219728',	'rsybbe37@opensource.org',	'Maywood',	'Lancaster',	'Pennsylvania',	17605
EXECUTE ADD_CUSTOMER (NULL, 6, 'Edik',	'Craze',	'397325908',	'ecraze38@dagondesign.com',	'Spaight',	'El Paso',	'Texas',	88541
EXECUTE ADD_CUSTOMER (NULL, 5, 'Drew',	'Oxtoby',	'586024583',	'doxtoby39@booking.com',	'Dottie',	'Alexandria',	'Virginia',	22333
EXECUTE ADD_CUSTOMER (NULL, 5, 'Nina	de', 'Courcey',	'788746733',	'ndecourcey3a@furl.net',	'Crownhardt',	'Baton Rouge',	'Louisiana',	70820
EXECUTE ADD_CUSTOMER (NULL, 4,  'NGarrott',	'Dainter',	'437057683',	'gdainter3b@npr.org',	'Dovetail',	'Waterbury',	'Connecticut',	6726
EXECUTE ADD_CUSTOMER (NULL, 4, 'Orran',	'Brister',	'251090801',	'obrister3c@exblog.jp	Vahlen',	'Kansas', 'City	Missouri',	64114
EXECUTE ADD_CUSTOMER (5, NULL, 'Yorke',	'Kearns',	'467895075',	'ykearns3d@ucsd.edu',	'Starling',	'Myrtle Beach',	'South Carolina',	29579
EXECUTE ADD_CUSTOMER (5, NULL, 'Verne',	'Ellerker',	'271372315',	'vellerker3e@moonfruit.com',	'Eliot',	'Abilene',	'Texas',	79605
EXECUTE ADD_CUSTOMER (6, NULL, 'Grenville',	'Jagoe',	'493305248',	'gjagoe3f@cnn.com',	'Loomis',	'Dallas',	'Texas',	75221
EXECUTE ADD_CUSTOMER (7, NULL, 'Audre',	'Tesdale',	'101697752',	'atesdale3g@cafepress.com',	'Northview',	'Columbia',	'South Carolina',	29215
EXECUTE ADD_CUSTOMER (7, NULL, 'Knox',	'Waything',	'375571330',	'kwaything3h@ocn.ne.jp',	'Harper',	'Montgomery',	'Alabama',	36109
EXECUTE ADD_CUSTOMER (3, NULL, 'Gwenora',	'Habbema',	'610578552',	'ghabbema3i@amazonaws.com',	'Coolidge',	'San Antonio',	'Texas',	78296
EXECUTE ADD_CUSTOMER (3, NULL, 'Chrysler',	'Remon',	'333546670',	'cremon3j@w3.org',	'Melvin',	'Sacramento',	'California',	95828
EXECUTE ADD_CUSTOMER (NULL, 10, 'Charmain',	'Castangia',	'756486445',	'ccastangia3k@cargocollective.com',	'Almo',	'Raleigh',	'North Carolina',	27621
EXECUTE ADD_CUSTOMER (4, NULL, 'Paton',	'Birchwood',	'891284352',	'pbirchwood3l@wisc.edu',	'Springs',	'San Bernardino',	'California',	92410
EXECUTE ADD_CUSTOMER (5, NULL, 'Roscoe',	'McCaughren',	'549586282',	'rmccaughren3m@gnu.org',	'Lerdahl',	'New Orleans',	'Louisiana',	70142
EXECUTE ADD_CUSTOMER (6, NULL, 'Miltie',	'Plewes',	'744235499',	'mplewes3n@netscape.com	', 'Pond Van', 'Nuys',	'California',	91411
EXECUTE ADD_CUSTOMER (7, NULL, 'Waldon',	'Brind',	'300650086',	'wbrind3o@hubpages.com',	'Kensington',	'Kansas City',	'Missouri',	64101
EXECUTE ADD_CUSTOMER (NULL, 8, 'Christye',	'Marti',	'357697756',	'cmarti3p@miitbeian.gov.cn',	'Waxwing',	'Katy',	'Texas',	77493
EXECUTE ADD_CUSTOMER (NULL, 8, 'Margalo',	'Mountain',	'273072220',	'mmountain3q@printfriendly.com',	'Heath',	'Minneapolis',	'Minnesota',	55480
EXECUTE ADD_CUSTOMER (NULL, 9, 'Ellynn',	'Castiglioni',	'566186189',	'ecastiglioni3r@netscape.com',	'Old Gate',	'Palm Bay',	'Florida',	32909
EXECUTE ADD_CUSTOMER (NULL, 9, 'Phip',	'Siviour',	'645033867',	'psiviour3s@wufoo.com',	'Summerview',	'Miami',	'Florida',	33283
EXECUTE ADD_CUSTOMER (NULL, 2, 'Basilius',	'Tilson',	'708467625',	'btilson3t@go.com',	'Fairfield',	'Richmond',	'Virginia',	23220
EXECUTE ADD_CUSTOMER (NULL, 2, 'Osborn',	'Marguerite',	'400350606',	'omarguerite3u@narod.ru',	'Eagle Crest',	'Raleigh',	'North Carolina',	27635
EXECUTE ADD_CUSTOMER (NULL, 3, 'Benni',	'Salkeld',	'737618102',	'bsalkeld3v@goo.gl',	'Almo',	'Metairie',	'Louisiana',	70005
EXECUTE ADD_CUSTOMER (NULL, 4, 'Aldon',	'Duerden',	'522914618',	'aduerden3w@cornell.edu',	'Darwin',	'Cambridge',	'Massachusetts',	2142
EXECUTE ADD_CUSTOMER (NULL, 4, 'Krystalle',	'Mc Ilory',	'748346851',	'kmcilory3x@archive.org',	'Pankratz',	'Tyler',	'Texas',	75705
EXECUTE ADD_CUSTOMER (NULL, 5, 'Findlay',	'Wrigley',	'533590611',	'fwrigley3y@shareasale.com',	'Surrey',	'Hialeah',	'Florida',	33018
EXECUTE ADD_CUSTOMER (NULL, 5, 'Pepe',	'Hebble',	'171599842',	'phebble3z@answers.com',	'Autumn Leaf',	'Madison',	'Wisconsin',	53710
EXECUTE ADD_CUSTOMER (NULL, 4, 'Jess',	'Fiennes',	'237171489',	'jfiennes40@symantec.com',	'Fremont',	'Albany',	'New York',	12242
EXECUTE ADD_CUSTOMER (8, NULL, 'Alli',	'De Bruin',	'279697153',	'adebruin41@economist.com',	'Springview',	'Portland',	'Oregon',	97216
EXECUTE ADD_CUSTOMER (8, NULL, 'Standford'	'Igoe',	'387572782',	'sigoe42@booking.com',	'Sage',	'Grand Rapids',	'Michigan',	49505
EXECUTE ADD_CUSTOMER (7, NULL, 'Baryram',	'Banasiak',	'564050166',	'bbanasiak43@unblog.fr',	'Mayfield',	'San Antonio',	'Texas',	78255
EXECUTE ADD_CUSTOMER (7, NULL, 'Urbain',	'Steagall',	'440085461',	'usteagall44@amazon.de',	'Fisk',	'Anchorage',	'Alaska',	99512
EXECUTE ADD_CUSTOMER (6, NULL, 'Aldin',	'Myles',	'407214161',	'amyles45@sun.com',	'Marcy',	'Boulder',	'Colorado',	80328
EXECUTE ADD_CUSTOMER (6, NULL, 'Tamas',	'MacCurlye',	'479314434',	'tmaccurlye46@csmonitor.com',	'Hagan',	'Houston',	'Texas',	77005
EXECUTE ADD_CUSTOMER (5, NULL, 'Gus',	'Tukesby',	'461252859',	'gtukesby47@newsvine.com',	'Anderson',	'Cincinnati',	'Ohio',	45223
EXECUTE ADD_CUSTOMER (8, NULL, 'Gan',	'McKimmie',	'505343976',	'gmckimmie48@bandcamp.com',	'Chinook',	'Miami',	'Florida',	33175
EXECUTE ADD_CUSTOMER (8, NULL, 'Jayme',	'Sitlington',	'267565754',	'jsitlington49@youtu.be',	'Lindbergh',	'Birmingham',	'Alabama',	35242
EXECUTE ADD_CUSTOMER (3, NULL, 'Caril',	'Shoebotham',	'242606101',	'cshoebotham4a@gizmodo.com',	'Rockefeller',	'Kansas City',	'Missouri',	64199
EXECUTE ADD_CUSTOMER (3, NULL, 'April',	'Parchment',	'477585365',	'aparchment4b@examiner.com',	'Merrick',	'Bloomington',	'Indiana'	47405
EXECUTE ADD_CUSTOMER (NULL, 1, 'Bernadine',	'Croizier',	'712936777',	'bcroizier4c@cisco.com',	'Valley Edge',	'Mc Keesport',	'Pennsylvania',	15134
EXECUTE ADD_CUSTOMER (NULL, 1, 'Vasily',	'Golthorpp',	'695648536',	'vgolthorpp4d@example.com',	'Warrior',	'Plano',	'Texas',	75074
EXECUTE ADD_CUSTOMER (NULL, 2, 'Jacki',	'Stibbs',	'279063682',	'jstibbs4e@china.com.cn',	'Sachs',	'Reno',	'Nevada',	89505
EXECUTE ADD_CUSTOMER (NULL, 2, 'Lorens',	'Tinton',	'709095534',	'ltinton4f@bbb.org',	'5th	Cape', 'Coral',	'Florida',	33915
EXECUTE ADD_CUSTOMER (NULL, 3, 'Valencia',	'Ripley',	'424023616',	'vripley4g@blogtalkradio.com',	'Troy',	'Springfield',	'Ohio',	45505
EXECUTE ADD_CUSTOMER (NULL, 3, 'Beatriz',	'Clemintoni',	'230434268',	'bclemintoni4h@e-recht24.de',	'Anniversary',	'Lincoln',	'Nebraska',	68583
EXECUTE ADD_CUSTOMER (NULL, 4, 'Stafani',	'Dumper',	'151769393',	'sdumper4i@cisco.com',	'Lighthouse Bay',	'Bradenton',	'Florida',	34210
EXECUTE ADD_CUSTOMER (NULL, 4, 'Arabel',	'Robb'	'887549117',	'arobb4j@nationalgeographic.com',	'Sauthoff',	'Washington'	'District of Columbia',	20010
EXECUTE ADD_CUSTOMER (NULL, 5, 'Oneida',	'Karel',	'702783830',	'okarel4k@flavors.me',	'Vidon',	'Van Nuys',	'California',	91406
EXECUTE ADD_CUSTOMER (NULL, 5, 'Courtney',	'Campanelli',	'238501760',	'ccampanelli4l@go.com',	'Onsgard',	'Anchorage',	'Alaska',	99507
EXECUTE ADD_CUSTOMER (NULL, 10, 'Annabal',	'Doberer',	'839480787',	'adoberer4m@a8.net',	'Mendota',	'Wilmington',	'Delaware',	19892
EXECUTE ADD_CUSTOMER (NULL, 10, 'Alric',	'Horick',	'610210854',	'ahorick4n@google.com.br',	'Harper',	'Newark',	'Delaware',	19714
EXECUTE ADD_CUSTOMER (NULL, 7, 'Court',	'Frill',	'526264405',	'cfrill4o@sohu.com',	'Chinook',	'Canton',	'Ohio',	44705
EXECUTE ADD_CUSTOMER (1, NULL, 'Kayne',	'Jirieck',	'209557837',	'kjirieck4p@google.ca',	'Packers',	'Austin',	'Texas',	78764
EXECUTE ADD_CUSTOMER (1, NULL, 'Jabez',	'Dibdall',	'531968114',	'jdibdall4q@cdbaby.com',	'Ronald', 'Regan Salt Lake City',	'Utah',	84120
EXECUTE ADD_CUSTOMER (2, NULL, 'Annabela',	'Lorant',	'756451097',	'alorant4r@bizjournals.com',	'1st',	'Dallas',	'Texas',	75310
EXECUTE ADD_CUSTOMER (2, NULL, 'Farrell',	'Mulberry',	'838755947',	'fmulberry4s@etsy.com',	'Hallows',	'Syracuse',	'New York',	13224
EXECUTE ADD_CUSTOMER (3, NULL, 'Korry',	'Wellan',	'112829485',	'kwellan4t@ehow.com',	'Lakewood',	'Philadelphia',	'Pennsylvania',	19178
EXECUTE ADD_CUSTOMER (3, NULL, 'Marlie',	'Flemming',	'158100376',	'mflemming4u@jalbum.net',	'3rd',	'Virginia Beach',	'Virginia',	23464
EXECUTE ADD_CUSTOMER (4, NULL, 'Norris',	'Spinige',	'445227351',	'nspinige4v@rambler.ru',	'Namekagon',	'Staten Island',	'New York',	10305
EXECUTE ADD_CUSTOMER (4, NULL, 'Anabel',	'Lethbrig',	'582137267',	'alethbrig4w@sitemeter.com',	'Oak Valley',	'Portland',	'Maine',	4109
EXECUTE ADD_CUSTOMER (5, NULL, 'Gwenette',	'Aleksandrov',	'324851152',	'galeksandrov4x@npr.org',	'Eliot',	'Independence',	'Missouri',	64054
EXECUTE ADD_CUSTOMER (5, NULL, 'Pen',	'Sibary',	'323143064',	'psibary4y@utexas.edu',	'Ruskin',	'Springfield',	'Missouri',	65898
EXECUTE ADD_CUSTOMER (6, NULL, 'Sidoney',	'Cicccitti',	'101301730',	'scicccitti4z@skyrock.com',	'Fieldstone',	'Seattle',	'Washington',	98104
EXECUTE ADD_CUSTOMER (6, NULL, 'Eve', 'Crosfield',	'278407636',	'ecrosfield50@who.int',	'North',	'Nashville',	'Tennessee',	37215
EXECUTE ADD_CUSTOMER (7, NULL, 'Erik',	'Prangnell',	'350292097',	'eprangnell51@123-reg.co.uk',	'7th',	'Portland',	'Oregon',	97255
EXECUTE ADD_CUSTOMER (7, NULL, 'Nariko',	'Kondratovich',	'583532086',	'nkondratovich52@huffingtonpost.com',	'Coleman',	'Seattle',	'Washington',	98115
EXECUTE ADD_CUSTOMER (8, NULL, 'Muffin',	'Dilley',	'277779986',	'mdilley53@desdev.cn',	'Fremont',	'New York City',	'New York',	10060
EXECUTE ADD_CUSTOMER (NULL, 10, 'Almeta',	'Simenon',	'813596671',	'asimenon54@blogs.com',	'Redwing',	'Billings',	'Montana',	59112
EXECUTE ADD_CUSTOMER (NULL, 10, 'Tasha',	'Abdon',	'531208977',	'tabdon55@yelp.com',	'David',	'Trenton',	'New Jersey',	8619
EXECUTE ADD_CUSTOMER (NULL, 9, 'Roth',	'Warrier',	'844368330',	'rwarrier56@github.io',	'Lakeland',	'Stamford',	'Connecticut',	6922
EXECUTE ADD_CUSTOMER (NULL, 9,  'My',	'Hampe',	'473299337',	'mhampe57@csmonitor.com',	'Arizona',	'Pueblo',	'Colorado',	81010
EXECUTE ADD_CUSTOMER (NULL, 8, 'Sheree',	'Merner',	'866051492',	'smerner58@sina.com.cn',	'Schurz',	'Cincinnati',	'Ohio',	45218
EXECUTE ADD_CUSTOMER (NULL, 8, 'Nolie',	'Adkin',	'380439573',	'nadkin59@blogs.com',	'Manufacturers',	'Littleton',	'Colorado',	80127
EXECUTE ADD_CUSTOMER (NULL, 8 'Candie',	'Chapell',	'328036958',	'cchapell5a@dailymotion.com',	'Lillian',	'Mountain View',	'California',	94042
EXECUTE ADD_CUSTOMER (NULL, 7, 'Eartha',	'Fandrey',	'482449409',	'efandrey5b@huffingtonpost.com',	'Bobwhite',	'Houston',	'Texas',	77025
EXECUTE ADD_CUSTOMER (NULL, 7, 'Bald',	'Demange',	'157374020',	'bdemange5c@elpais.com',	'Katie',	'Waltham',	'Massachusetts',	2453
EXECUTE ADD_CUSTOMER (NULL, 6, 'Darsie',	'Abrehart',	'352152230',	'dabrehart5d@salon.com',	'Badeau',	'Sacramento',	'California',	95818
EXECUTE ADD_CUSTOMER (NULL, 6, 'Justus',	'Fairbrace',	'272157815',	'jfairbrace5e@sogou.com',	'Brentwood',	'Atlanta',	'Georgia',	30301
EXECUTE ADD_CUSTOMER (NULL, 5, 'Ros',	'Niaves',	'244972508',	'rniaves5f@kickstarter.com',	'Bayside', 	'Houston',	'Texas'	77080
EXECUTE ADD_CUSTOMER (NULL 4, 'Crosby',	'Johnson',	'121681958',	'cjohnson5g@comcast.net',	'Rowland',	'San Francisco',	'California'	94159
EXECUTE ADD_CUSTOMER (NULL, 3, 'Kiele',	'Benediktsson',	'833840609',	'kbenediktsson5h@alexa.com',	'Onsgard',	'New York City',	'New York',	10110
EXECUTE ADD_CUSTOMER (NULL, 2, 'Putnem',	'McKeating',	'390240474',	'pmckeating5i@sciencedaily.com',	'Starling',	'Pensacola',	'Florida'	32520
EXECUTE ADD_CUSTOMER (NULL, 1, 'Sonia',	'Olyff',	'370187832','solyff5j@java.com',	'Fulton',	'Miami',	'Florida'	33283);



EXECUTE ADD_POLICY(1, 1,'06-FEB-23');
EXECUTE ADD_POLICY(2, 1,'09-JAN-24');
EXECUTE ADD_POLICY(3, 1,'11-DEC-25');
EXECUTE ADD_POLICY(4, 2,'19-NOV-27');
EXECUTE ADD_POLICY(5, 2,'22-JULY-29');
EXECUTE ADD_POLICY(6, 2,'19-AUG-31');
EXECUTE ADD_POLICY(7, 2,'16-JUN-27');
EXECUTE ADD_POLICY(8, 3,'28-MARCH-23');
EXECUTE ADD_POLICY(9, 3,'15-APRIL-26');
EXECUTE ADD_POLICY(10, 3,'19-MAY-33');
EXECUTE ADD_POLICY(11, 4,'07-AUG-24');
EXECUTE ADD_POLICY(12, 4,'16-FEB-25');
EXECUTE ADD_POLICY(13, 5,'23-APRIL-28');
EXECUTE ADD_POLICY(14, 5,'19-JAN-26');
EXECUTE ADD_POLICY(15, 5,'30-SEP-31');
EXECUTE ADD_POLICY(16, 5,'12-OCT-27');


EXECUTE ADD_PATIENT(1, 'JOHN', 'MICH', 'SELF','10/03/1993');
EXECUTE ADD_PATIENT(2, 'JACK', 'ROY', 'SELF','04/15/2000');
EXECUTE ADD_PATIENT(3, 'CHARL', 'HARRIS','FATHER','02/21/1966');
EXECUTE ADD_PATIENT(4, 'SAHIL', 'JOSHI','SELF','06/11/1999');
EXECUTE ADD_PATIENT(5, 'SMITA', 'RAUT','MOTHER','01/02/1977');
EXECUTE ADD_PATIENT(6, 'RAJESH', 'NAGPURKAR','BROTHER','08/09/2010');
EXECUTE ADD_PATIENT(7, 'SITA', 'PATEL','SELF','11/23/1993');
EXECUTE ADD_PATIENT(8, 'VIJAYA', 'DEV','WIFE','07/22/1995');
EXECUTE ADD_PATIENT(9, 'SWAROOPA', 'LAXMI','SELF','09/9/1989');
EXECUTE ADD_PATIENT(10, 'SAYLI', 'KUMAR', 'SISTER','12/07/2002');
EXECUTE ADD_PATIENT(11, 'AJAY', 'SHAIKH', 'HUSBAND','01/16/1988');
EXECUTE ADD_PATIENT(12, 'RAVI', 'JOSHI', 'BROTHER','10/26/2012');
EXECUTE ADD_PATIENT(13, 'TEJASWINI', 'NANDALA', 'SELF','02/06/1982');
EXECUTE ADD_PATIENT(14, 'MONIKA', 'MOVVA', 'WIFE','09/23/1990');
EXECUTE ADD_PATIENT(15, 'MEENA', 'DHOLE', 'MOTHER','08/14/1962');
EXECUTE ADD_PATIENT(16, 'SUNIL', 'DAMLE', 'FATHER','02/28/1977');


EXECUTE ADD_HOSPITAL('MASSACHUSETTS GENERAL HOSPITAL', '275 CAMBRIDGE ST', 'BOSTON', 'MASSACHUSETTS', 02114);
EXECUTE ADD_HOSPITAL('BOSTON EYE CARE', '126 HIGH ST', 'BOSTON', 'MASSACHUSETTS', 02110 );
EXECUTE ADD_HOSPITAL('NEWTON MEDICAL CENTER', '175 HIGH ST', 'NEWTON', 'NEW JERSEY', 07860);
EXECUTE ADD_HOSPITAL('HOUSTON METHODIST HOSPITAL', '6565 FANNIN ST', 'HOUSTON', 'TEXAS', 77030);
EXECUTE ADD_HOSPITAL('GULF COAST MEDICAL CENTER', '13681 DOCTORS WAY', 'FORT MYERS', 'FLORIDA', 33912);
EXECUTE ADD_HOSPITAL('UNIVERSITY HOSPITAL', '150 BERGEN ST', 'NEWARK', 'NEW JERSEY', 07103);
EXECUTE ADD_HOSPITAL('MEDICAL CITY DALLAS', '7777 FOREST LN', 'DALLAS', 'TEXAS', 75230);
EXECUTE ADD_HOSPITAL('DENVER HEALTH', '777 BANNOCK ST', 'DENVER', 'COLORADO', 80204);
EXECUTE ADD_HOSPITAL('SOUTHERN CALIFORNIA HOSPITAL', '3828 DELMAS TERRACE', 'CULVER CITY', 'CALIFORNIA', 90232);
EXECUTE ADD_HOSPITAL('ROSE MEDICAL CENTER', '4567 E9TH AVE', 'DENVER', 'COLORADO', 80220);
EXECUTE ADD_HOSPITAL('FOOTHILLS HOSPTAL', '4747 ARAPAHOE AVE', 'BOULDER', 'COLORADO', 80303);

EXECUTE ADD_DOCTOR(1, 'DR. HANI B', 'BARADI', 'OPTHOMOLOGY');
EXECUTE ADD_DOCTOR(1, 'DR. NAJJIA', 'MAHMOUD', 'CARDIOLOGY');
EXECUTE ADD_DOCTOR(2, 'DR. SANKAR NAIDU', 'ADUSUMILLI', 'NEUROLOGY');
EXECUTE ADD_DOCTOR(2, 'DR. LANCE KYLE', 'BURNS', 'ONGOLOGY');
EXECUTE ADD_DOCTOR(3, 'DR. VIKRAM B', 'REDDY', 'OPTHOMOLOGY');
EXECUTE ADD_DOCTOR(4, 'DR. STEVENS N', 'CARTER', 'RADIOLOGY');
EXECUTE ADD_DOCTOR(5, 'DR. VIRGILIO V', 'GEORGE', 'NEPHROLOGY');
EXECUTE ADD_DOCTOR(6, 'DR. CRAIG S', 'JOHNSON', 'ONGOLOGY');
EXECUTE ADD_DOCTOR(7, 'DR. FREDERICK J', 'DENSTMAN', 'NEPHROLOGY');
EXECUTE ADD_DOCTOR(8, 'DR. SANJAU G', 'KHICHA', 'DERMATOLOGY');
EXECUTE ADD_DOCTOR(9, 'DR NEPAL C', 'CHOWDHURY', 'GASTROENTOLOGY');
EXECUTE ADD_DOCTOR(10, 'DR. JAMES E', 'DAVIES', 'GENERAL SURGERY');
EXECUTE ADD_DOCTOR(11, 'DR. SHAMSUDDIN', 'KHWAJA', 'PULMONOLOGY');
EXECUTE ADD_DOCTOR(11, 'DR. PRASHANTH', 'CHOWDHARY', 'NEPHROLOGY');
EXECUTE ADD_DOCTOR(11, 'DR. WILLIAM F', 'TURNER', 'CARDIOLOGY');
SELECT * FROM DOCTOR;
EXECUTE ADD_TREATMENT(1,1,'EYE INFECTION');
EXECUTE ADD_TREATMENT(2,2,'CARDIAC ATTACK');
EXECUTE ADD_TREATMENT(12,3,'SURGERY');
EXECUTE ADD_TREATMENT(5,4,'EYE CHECKUP');
EXECUTE ADD_TREATMENT(6,5,'CANCER TREATMENT');
EXECUTE ADD_TREATMENT(8,6,'CHEMO THERAPY');
EXECUTE ADD_TREATMENT(8,7,'THROAT CANCER');
EXECUTE ADD_TREATMENT(14,8,'KIDNEY DIALISIS');
EXECUTE ADD_TREATMENT(10,9,'SKIN ALLERGY');
EXECUTE ADD_TREATMENT(11,10,'STOMACHACHE');
EXECUTE ADD_TREATMENT(10,11,'OP(CYST)');
EXECUTE ADD_TREATMENT(15,12,'ASTHAMA');
EXECUTE ADD_TREATMENT(9,13,'KIDNEY TRANSPLANT');
EXECUTE ADD_TREATMENT(6,14,'BLOOD CANCER');
EXECUTE ADD_TREATMENT(2,15,'BYPASS SURGERY');
EXECUTE ADD_TREATMENT(3,16,'NEURO STROKE');

select * from hospital;
select * from treatment;
select * from doctor;
--ddmmyyyy
EXECUTE ADD_BILL(1,1,'09-MAY-2021',600);
EXECUTE ADD_BILL(2,1,'23-NOV-2018',3548);
EXECUTE ADD_BILL(3,10,'16-MAR-2013',1067);
EXECUTE ADD_BILL(4,3,'05-SEP-2020',800);
EXECUTE ADD_BILL(5,4,'12-FEB-2018',9450);
EXECUTE ADD_BILL(6,6,'18-AUG-2014',2067);
EXECUTE ADD_BILL(7,6,'30-APR-2022',9800);
EXECUTE ADD_BILL(8,11,'01-JULY-2009',10000);
EXECUTE ADD_BILL(9,8,'25-SEP-2021',3190);
EXECUTE ADD_BILL(10,9,'19-NOV-2017',7900);
EXECUTE ADD_BILL(11,8,'02-AUG-2021',4020);
EXECUTE ADD_BILL(12,11,'16-APR-2019',1000);
EXECUTE ADD_BILL(13,7,'07-JUL-2014',1730);
EXECUTE ADD_BILL(14,4,'10-MAR-2009',3500);
EXECUTE ADD_BILL(15,1,'03-SEP-2013',5200);
EXECUTE ADD_BILL(16,2,'01-DEC-2010',7800);



EXECUTE ADD_CLAIM(1, 1, 600, '10-MAY-2021','APPROVED');
EXECUTE ADD_CLAIM(2, 2, 3548, '24-NOV-2018','PENDING');
EXECUTE ADD_CLAIM(3, 3, 1067, '17-MAR-2013','APPROVED');
EXECUTE ADD_CLAIM(4, 4, 800, '06-SEP-2020','APPROVED');
EXECUTE ADD_CLAIM(5, 5, 9450, '13-FEB-2018','REJECTED');
EXECUTE ADD_CLAIM(6, 6, 2067, '19-AUG-2014','PENDING');
EXECUTE ADD_CLAIM(7, 7, 9800, '01-MAY-2022','REJECTED');
EXECUTE ADD_CLAIM(8, 8, 10000, '02-JUL-2009','APPROVED');
EXECUTE ADD_CLAIM(9, 9, 3190, '26-SEP-2021','PENDING');
EXECUTE ADD_CLAIM(10, 10, 7900, '20-NOV-2017','APPROVED');
EXECUTE ADD_CLAIM(11, 11, 4020, '03-AUG-2021','PENDING');
EXECUTE ADD_CLAIM(12, 12, 1000, '17-APR-2019','APPROVED');
EXECUTE ADD_CLAIM(13, 13, 1730, '08-JUL-2014','APPROVED');
EXECUTE ADD_CLAIM(14, 14, 3500, '11-MAR-2009','REJECTED');
EXECUTE ADD_CLAIM(15, 15, 5200, '04-SEP-2013','PENDING');
EXECUTE ADD_CLAIM(16, 16, 7800, '02-DEC-2010','APPROVED');
/*
SELECT * FROM BILL;

SELECT B.BILL_ID,C.CUSTOMER_ID,py.policy_no
FROM BILL B  LEFT JOIN TREATMENT T ON B.TREATMENT_ID=T.TREATMENT_ID
JOIN  PATIENT P ON T.PATIENT_ID=P.PATIENT_ID
JOIN CUSTOMER C ON C.CUSTOMER_ID=P.CUSTOMER_ID
JOIN POLICY PY ON C.CUSTOMER_ID=PY.CUSTOMER_ID;


SELECT * FROM TREATMENT;

SELECT * FROM POLICY;
SELECT * FROM BILL;
SELECT * FROM PATIENT;


Select C.CLAIM_ID,C.CLAIM_AMOUNT,C.STATUS,SC.FIRST_NAME,SC.LAST_NAME
from claim C JOIN BILL B ON C.BILL_ID=B.BILL_ID
JOIN TREATMENT T ON B.TREATMENT_ID=T.TREATMENT_ID
JOIN PATIENT P ON P.PATIENT_ID=T.PATIENT_ID
JOIN CUSTOMER SC ON P.CUSTOMER_ID=SC.CUSTOMER_ID
where CLAIM_AMOUNT>5000 AND status='APPROVED'
ORDER BY C.CLAIM_AMOUNT ASC;
*/